name = "sfexpress-database"
main = "worker.js"
compatibility_date = "2026-01-01"

# Phục vụ file tĩnh (index.html) từ thư mục public/
[assets]
directory = "./public"
binding = "ASSETS"

# D1 database đã tạo trên Cloudflare Dashboard
[[d1_databases]]
binding = "DB"
database_name = "sfexpress-database"
database_id = "9f73f138-4046-4bd7-a865-be58bb57b747"
